# Copyright 2022 Adaltas
# SPDX-License-Identifier: MIT

---
roles:
  - name: cloudalchemy.prometheus
    src: https://github.com/cloudalchemy/ansible-prometheus.git
    version: 4.0.0
  - name: cloudalchemy.grafana
    version: 0.18.0
