# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- include_role:
    name: cloudalchemy.grafana
    tasks_from: preflight

- include_role:
    name: cloudalchemy.grafana
    tasks_from: install
